---
- name: Set tags
  tags:
    - always
    - deprecations
  block:
    - name: Image prepare parameters
      import_tasks: image-prepare.yaml
    - name: Misc params
      import_tasks: misc.yaml
