- name: common tags
  tags:
    - config
    - scripts
    - builder-bootstrap
    - lab
  block:
    - name: push helper scripts
      copy:
        dest: /usr/local/bin/
        group: root
        mode: '0755'
        owner: root
        src: "{{ item }}"
      with_fileglob: 'scripts/lab-*'

    - name: push lab-destroy template
      template:
        dest: /usr/local/bin/lab-destroy
        group: root
        mode: '0755'
        owner: root
        src: scripts/lab-destroy.j2
