---
- name: if ceph is requested
  when: standalone_ceph|bool
  become: true
  become_user: root
  block:
    - name: install lvm2
      package:
        name: lvm2
        state: installed

    - name: create loop devices
      command: dd if=/dev/zero of=/var/lib/ceph-osd.img bs=1 count=0 seek=7G
      args:
        creates: /var/lib/ceph-osd.img

    - name: run losetup
      command: losetup /dev/loop3 /var/lib/ceph-osd.img
      args:
        creates: /dev/loop3

    - name: create backup directory
      file:
        path: /root/ceph_ansible_fetch
        state: directory

    - name: create LVM things for ceph
      shell: |
        pvcreate /dev/loop3
        vgcreate ceph_vg /dev/loop3
        lvcreate -n ceph_lv_wal -l 375 ceph_vg
        lvcreate -n ceph_lv_db -l 375 ceph_vg
        lvcreate -n ceph_lv_data -l 1041 ceph_vg
      args:
        creates: /dev/mapper/ceph_vg-ceph_lv_wal

- name: ceph params if requested
  when: standalone_ceph|bool
  copy:
    dest: /home/stack/ceph_parameters.yaml
    src: standalone_ceph.yaml
