---
- name: Generate standalone environment
  set_fact:
    standalone_env_files: |-
      /usr/share/openstack-tripleo-heat-templates/environments/standalone/standalone-tripleo.yaml
      {% if standalone_ceph|bool %}
      /usr/share/openstack-tripleo-heat-templates/environments/ceph-ansible/ceph-ansible.yaml
      {% endif %}
      {% if standalone_ceph|bool %}
      /home/stack/ceph_parameters.yaml
      {% endif %}
      {% for env in additional_envs %}
      {{ env }}
      {% endfor %}
      /home/stack/generated-container-prepare.yaml
      /home/stack/standalone_parameters.yaml

- name: deploy standalone
  when: deploy_standalone|bool
  import_role:
    name: tripleo.operator.tripleo_deploy
  vars:
    tripleo_deploy_standalone: true
    tripleo_deploy_output_dir: /home/stack
    tripleo_deploy_environment_files: "{{ standalone_env_files.split('\n') }}"
    tripleo_deploy_local_ip: '192.168.24.2'
