---
- name: install lvm2 needed by cinder
  become: true
  become_user: root
  package:
    name: lvm2
    state: installed

- name: Unmanage eth1
  become: true
  become_user: root
  when:
    - os_version > 7
  command: nmcli dev set eth1 managed no

- name: basic parameters for standalone
  template:
    dest: /home/stack/standalone_parameters.yaml
    src: standalone_params.yaml.j2

- name: octavia param
  copy:
    dest: /home/stack/octavia-param.yaml
    src: standalone_octavia.yaml
