---
- name: Get certmonger local CA
  tags:
    - lab
    - overcloud
  when:
    - enable_tls|default(False)|bool
  slurp:
    src: /etc/pki/ca-trust/source/anchors/cm-local-ca.pem
  register: certmonger_ca

- name: Inject certmonger CA in overcloud env file
  tags:
    - lab
    - overcloud
  when:
    - enable_tls|default(False)|bool
  template:
    dest: /home/stack/tls-inject-ca.yaml
    src: tls-inject-ca.yaml.j2
    group: stack
    mode: 0644
    owner: stack

- name: create image directory
  tags:
    - lab
    - overcloud
    - baremetal
    - overcloud-images
  file:
    path: "/home/stack/overcloud_imgs"
    state: directory

- name: update the ctlplane-subnet dns server
  when:
    - deploy_undercloud|bool
  tags:
    - lab
    - baremetal
    - overcloud
  shell: |
    source ~/stackrc
    openstack subnet show ctlplane-subnet -f json | jq '.dns_nameservers' | grep "{{ undercloud_dns }}" ||
    openstack subnet set ctlplane-subnet --dns-nameserver {{ undercloud_dns }}

- name: Get generated role-data
  tags:
    - lab
    - baremetal
    - overcloud
  command: openstack overcloud roles generate -o /tmp/roledata.yaml Compute Controller CephStorage
  args:
    creates: /tmp/roledata.yaml

- name: Update networks in role-data
  tags:
    - lab
    - baremetal
    - overcloud
  include_tasks: update-network-role.yaml
  loop: "{{ overclouds_range }}"
