- name: run on undercloud node
  tags:
    - lab
  block:
    - name: Gather facts
      setup:
        gather_subset: 'all'

    - name: Set some local facts|vars
      set_fact:
        base_image: "{{ ansible_facts['distribution'] | lower }}"
        overclouds_range: "{{ range(0, overclouds | default(1)) | list }}"

    - name: Configure upstream repository
      when:
        - base_image == 'centos'
      include_role:
        name: tripleo.operator.tripleo_repos
      vars:
        tripleo_repos_extra_repos:
          - ceph
        tripleo_repos_version: "{{ tripleo_mod }}"
        tripleo_repos_branch: "{{ tripleo_version }}"

    - import_tasks: packages.yaml

    - import_tasks: prepare-build.yaml

    - name: CentOS package building
      tags:
        - custom-packages
      when:
        - base_image == 'centos'
      block:
        - import_tasks: pkg-build.yaml

    - name: Install built RPMs on CentOS
      tags:
        - custom-packages
      when:
        - base_image == 'centos'
      import_tasks: install-built-rpms.yaml

    - import_tasks: install-custom-selinux.yaml
    - import_tasks: remote-pkg.yaml
    - import_tasks: image-prepare.yaml
      tags: image-prepare
    - name: deploy standard undercloud and stuff
      when: not standalone|bool
      block:
        - import_tasks: prepare.yaml
        - name: deploy undercloud and prepare overcloud
          when:
            - deploy_undercloud|bool
          block:
            - import_tasks: deploy.yaml
    - name: prepare and deploy standalone
      when: standalone|bool
      block:
        - name: go for standalone
          import_role:
            role: standalone
