- name: install some tools
  become: true
  become_user: root
  package:
    name:
      - git
      - iotop
      - tmux
      - vim
    state: present

- name: install tripleo client
  become: true
  become_user: root
  package:
    name: "{{ tripleoclient_pkgname }}"
    state: present

- name: install requested packages for ceph
  become: true
  become_user: root
  package:
    name: [ceph-ansible, util-linux]
    state: installed

- name: Install network-scripts-openvswitch
  become: true
  become_user: root
  when:
    - base_image == 'centos'
    - os_version == 8
  package:
    name: network-scripts-openvswitch
