- name: let know tripleo-lab about custom container file
  set_fact:
    custom_container: "{{ modify_image|default([]) != [] }}"

- name: copy undercloud.conf sample
  copy:
    dest: /home/stack/undercloud.conf
    src: "{{ undercloud_sample }}"
    remote_src: true
    owner: stack
    group: stack
    mode: 0640

- name: Enable masquerading in undercloud.conf
  ini_file:
    path: /home/stack/undercloud.conf
    section: ctlplane-subnet
    option: masquerade
    value: "true"
    mode: 0640
    backup: false

- name: Set undercloud hostname
  ini_file:
    path: /home/stack/undercloud.conf
    section: DEFAULT
    option: undercloud_hostname
    value: "{{ undercloud_hostname | default('undercloud.localdomain') }}"
    mode: 0640
    backup: false

- name: Inject insecure registry in undercloud.conf
  ini_file:
    path: /home/stack/undercloud.conf
    section: DEFAULT
    option: container_insecure_registries
    value: undercloud.ctlplane
    backup: false

- name: inject container-prepare file in the undercloud.conf
  ini_file:
    path: /home/stack/undercloud.conf
    section: DEFAULT
    option: container_images_file
    value: /home/stack/containers-prepare-parameter.yaml
    backup: false

- name: Enable undercloud hieradata for low memory
  ini_file:
    path: /home/stack/undercloud.conf
    section: DEFAULT
    option: hieradata_override
    value: /home/stack/hieradata_undercloud_low_memory.yaml
    mode: 0640
    backup: false
  when: undercloud_low_memory|bool

- name: Create hieradata_undercloud_low_memory.yaml
  template:
    dest: /home/stack/hieradata_undercloud_low_memory.yaml
    src: hieradata_undercloud_low_memory.yaml.j2
  when: undercloud_low_memory|bool

- name: Disable SELinux if requested
  when: disable_selinux|default(False)|bool
  ini_file:
    backup: false
    path: /home/stack/undercloud.conf
    section: DEFAULT
    option: undercloud_enable_selinux
    value: 'false'

- name: Set undercloud NTP servers if needed
  when: NtpServer is defined
  ini_file:
    backup: false
    path: /home/stack/undercloud.conf
    section: DEFAULT
    option: undercloud_ntp_servers
    value: "{{ NtpServer | join(',') }}"

- name: include TLS config if needed
  when: enable_tls|default(False)|bool
  import_tasks: tls.yaml

- name: custom configuration in undercloud.conf
  ini_file:
    path: /home/stack/undercloud.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    mode: 0640
    backup: false
  loop: "{{ undercloud_config }}"
  loop_control:
    label: "{{ item.option }}"

- name: run commands as stack user
  become: true
  become_user: stack
  block:
    - name: generate baremetal.json file
      tags:
        - baremetal
      template:
        dest: /home/stack/baremetal.json
        mode: '0644'
        src: baremetal.json.j2

    - name: create per overcloud yml directory
      tags:
        - baremetal
      file:
        path: "/home/stack/overcloud-{{ item }}-yml"
        state: directory
      loop: "{{ range(0, overclouds)|list }}"

    - name: push common overcloud settings
      tags:
        - baremetal
      copy:
        dest: "/home/stack/"
        src: "{{ item }}"
      with_fileglob: 'files/overcloud/*.yaml'

    - name: push node placement
      tags:
        - baremetal
      template:
        dest: "/home/stack/overcloud-{{ item }}-yml/placement.yaml"
        src: node-placement.yaml.j2
      loop: "{{ range(0, overclouds)|list }}"

    - name: push scale setting
      tags:
        - baremetal
      template:
        dest: "/home/stack/overcloud-{{ item }}-yml/scale.yaml"
        src: scale.yaml.j2
      loop: "{{ range(0, overclouds)|list }}"

    - name: push per-overcloud network data
      tags:
        - baremetal
      template:
        dest: "/home/stack/oc{{ item }}-network-data.yaml"
        src: oc-network-data.yaml.j2
      loop: "{{ range(0, overclouds)|list }}"

    - name: push per-overcloud network env
      tags:
        - baremetal
      template:
        dest: "/home/stack/overcloud-{{ item }}-yml/network-env.yaml"
        src: oc-network-env.yaml.j2
      loop: "{{ range(0, overclouds)|list }}"

    - name: push ceph settings
      tags:
        - baremetal
      template:
        dest: "/home/stack/overcloud-{{ item }}-yml/ceph-params.yaml"
        src: ceph-params.yaml.j2
      loop: "{{ range(0, overclouds)|list }}"
      when:
        - vms|map(attribute='name')|select("match", '^ceph')|list|length > 0

    - name: push container-cli setting
      tags:
        - baremetal
      template:
        dest: "/home/stack/overcloud-{{ item }}-yml/container-cli.yaml"
        src: container-cli.yaml.j2
      loop: "{{ range(0, overclouds)|list }}"

    - name: push selinux setting
      tags:
        - baremetal
      template:
        dest: "/home/stack/overcloud-{{ item }}-yml/selinux-mode.yaml"
        src: oc-selinux.yaml.j2
      loop: "{{ range(0, overclouds)|list }}"

    - name: push basic deploy script
      tags:
        - baremetal
      template:
        dest: "/home/stack/deploy-overcloud-{{ item }}.sh"
        src: overcloud-deploy.sh.j2
        mode: 0750
      loop: "{{ range(0, overclouds)|list }}"

    - name: push push-oc-img script
      tags:
        - baremetal
      template:
        dest: /home/stack/push-oc-img
        src: push-oc-img
        mode: 0750

    - name: push config-download script
      tags:
        - baremetal
      template:
        dest: "/home/stack/config-download-oc{{ item }}.sh"
        src: overcloud-configdl.sh.j2
        mode: 0750
      loop: "{{ range(0, overclouds)|list }}"

    - name: create image directory
      tags:
        - baremetal
        - overcloud-images
      file:
        path: "/home/stack/overcloud_imgs"
        state: directory
