---
- name: install epel-release
  package:
    name: epel-release
    state: installed

- name: ensure epel is deactivated
  command: yum-config-manager --disable epel

- name: ensure epel-modular is deactivated
  command: yum-config-manager --disable epel-modular
