---
- name: fetch tmate release from github
  tags:
    - lab
    - undercloud-bootstrap
  command: "curl -OL https://github.com/tmate-io/tmate/releases/download/{{tmate_release}}/tmate-{{tmate_release}}-static-linux-amd64.tar.xz"
  args:
    creates: "/usr/src/tmate-{{tmate_release}}-static-linux-amd64.tar.xz"
    chdir: /usr/src

- name: uncompress tmate release
  tags:
    - lab
    - undercloud-bootstrap
  unarchive:
    creates: "/usr/src/tmate-{{tmate_release}}-static-linux-amd64"
    dest: /usr/src/
    src: "/usr/src/tmate-{{tmate_release}}-static-linux-amd64.tar.xz"
    remote_src: true

- name: copy tmate binary in path
  tags:
    - lab
    - undercloud-bootstrap
  copy:
    src: "/usr/src/tmate-{{tmate_release}}-static-linux-amd64/tmate"
    dest: "/usr/local/bin/tmate"
    remote_src: true
    mode: 0755

- name: configure tmate
  tags:
    - lab
    - undercloud-bootstrap
  copy:
    content: "{{ tmate_config|default('') }}"
    dest: /home/stack/.tmate.conf
    mode: 0600
    owner: stack
    group: stack
