---
- name: Ensure we get ceph repositories if needed
  tags:
    - lab
    - undercloud-bootstrap
  when:
    - vms|map(attribute='name')|select("match", '^ceph')|list|length > 0
    - '"ceph" not in tripleo_repos_repos'
  fail:
    msg: |
      Please activate ceph repository in tripleo_repos_repos list


