---
- name: run on nat-vm node
  tags:
    - nat-vm
    - lab
  delegate_to: nat-vm
  delegate_facts: false
  block:
    - name: Ensure we do not rely on GSS for auth
      replace:
        path: /etc/ssh/sshd_config
        regexp: '^GSSAPIAuthentication yes$'
        replace: 'GSSAPIAuthentication no'
      register: sshd_config

    - name: Restart sshd if needed
      service:
        name: sshd
        state: restarted
      when: sshd_config is changed

    - name: Remove dracute useless interface
      file:
        path: /etc/sysconfig/network-scripts/ifcfg-ens3
        state: absent

    - name: Add the 802.1q module
      modprobe:
        name: 8021q
        state: present

    - name: Configure eth1
      copy:
        dest: "/etc/sysconfig/network-scripts/ifcfg-eth1"
        content: |
          DEVICE="eth1"
          BOOTPROTO="none"
          ONBOOT="yes"
          TYPE="Ethernet"

    - name: Start eth1
      shell: ifup eth1

    - name: Create vlan interface
      command: |
        nmcli con add type vlan con-name vlan-{{ item+1 }}9 ifname eth1.{{ item+1 }}9 dev eth1 id {{ item+1 }}9 ip4 "10.20.{{ item+1 }}.1/24"
      args:
        creates: "/etc/sysconfig/network-scripts/ifcfg-vlan{{ item+1 }}9"
      loop: "{{ overclouds_range }}"
      loop_control:
        label: "vlan-{{item+1}}9"

    - name: Accept NAT
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present

    - name: Set MASQUERADE on POSTROUTING
      iptables:
        chain: POSTROUTING
        table: nat
        out_interface: eth0
        jump: MASQUERADE

    - name: Set FORWARD
      iptables:
        chain: FORWARD
        in_interface: eth1
        jump: ACCEPT
